version: "3"

services:
  llmt-workspace:
    image: omhq/llmt-workspace:0.0.2
    working_dir: /workspace
    volumes:
      - ./chats:/workspace/chats
      - ./files:/workspace/files
      - ./configs:/workspace/configs
      - ./udfs:/workspace/udfs

      # optionally mount the source code
      - ./llmt:/workspace/llmt
      - ./cli.py:/workspace/cli.py
    command: ["cli.py", "-f", "configs/config.yml"]
    environment:
      ROOT_PATH: /workspace
      DEBUG: "true"
